services:

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    stop_signal: SIGKILL
    ports:
      - 8000:8000

  database:
    image: postgres
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./database/db/:/var/lib/postgresql/data
      - ./database/logs:/logs